In [1]:
print("Arrays Indexing")

Arrays Indexing


In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0]

1

In [5]:
arr[2]

3

In [7]:
arr[1:5]

array([2, 3, 4, 5])

In [8]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [9]:
arr[1::2]

array([ 2,  4,  6,  8, 10])

In [10]:
print("Numpy Indexsing and Slicing of Matrix")

Numpy Indexsing and Slicing of Matrix


In [12]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
arr[0]

array([1, 2, 3, 4, 5])

In [14]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [15]:
arr[5]

array([26, 27, 28, 29, 30])

In [16]:
arr[0,0]

1

In [18]:
arr[0,4]

5

In [19]:
arr[5, 4]

30

In [21]:
slice_arr = arr[0:2, 1:3]
slice_arr

array([[2, 3],
       [7, 8]])

In [26]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [27]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

In [28]:
print("Boolen Indexing")

Boolen Indexing


In [29]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [31]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10])