In [1]:
print("Arrys Operations")

Arrys Operations


In [5]:
print("Arithmetic Operations")

Arithmetic Operations


In [6]:
import numpy as np

In [8]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([5, 6, 7, 8, 9])
a1
a2

array([5, 6, 7, 8, 9])

In [9]:
a1 + a2

array([ 6,  8, 10, 12, 14])

In [10]:
a1 - a2

array([-4, -4, -4, -4, -4])

In [11]:
a1 * a2

array([ 5, 12, 21, 32, 45])

In [12]:
a1 / a2

array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [13]:
a1 ** a2

array([      1,      64,    2187,   65536, 1953125])

In [14]:
print("Broadcasting")

Broadcasting


In [15]:
l = [10, 20, 30, 40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [16]:
arr + 10

array([20, 30, 40, 50])

In [17]:
print("Deeep, Shallow Copy")

Deeep, Shallow Copy


In [18]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [21]:
slice * 10

array([10, 20, 30, 40, 50])

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
copy = a[4:6]
copy

array([5, 6])

In [25]:
copy * 10

array([50, 60])

In [26]:
a
b =a

In [27]:
b[0] = 99

In [28]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
print("Matrix Operations")

Matrix Operations


In [32]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [33]:
A * B

array([[ 5, 12],
       [21, 32]])

In [34]:
A @ B

array([[19, 22],
       [43, 50]])

In [35]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [36]:
A

array([[1, 2],
       [3, 4]])

In [37]:
A.T

array([[1, 3],
       [2, 4]])

In [38]:
print("Advance Array Manipulation")

Advance Array Manipulation


In [39]:
print("Stacking Array")

Stacking Array


In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [43]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a
b

array([5, 6, 7, 8])

In [44]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [40]:
print("Splitiing Array")

Splitiing Array


In [47]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [52]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [53]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]