In [1]:
print("Valid Sudoku")

Valid Sudoku


In [8]:
import numpy as np

In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [7]:
s.sum()

405

In [15]:
print("Method 1")
b = np.sum(s, axis=1)
b == 45

Method 1


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [14]:
print("Method 2")
c = np.sum(s, axis=1)
for i in c:
    if i != 45:
        print("Suducu not Valid!")
        break
else:
    print("Suduku is valid!")

Method 2
Suduku is valid!


In [19]:
d = s[0:3, 0:3]
np.sum(d)

45

In [20]:
e = s[0:3, 3:6]
np.sum(e)

45

In [22]:
f = s[0:3, 6:9]
f
np.sum(f)

45

In [24]:
print(s)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [25]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3): 
        n = s[i:i+3, j: j + 3]
        print(n.sum())
        

45
45
45
45
45
45
45
45
45


In [11]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [12]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [13]:
#Find the average age of students.
data= np.mean(data[:,0])
data

18.4

In [17]:
#Extract Math marks of all students.
a = data[:, ]
a

IndexError: invalid index to scalar variable.

In [32]:
#Find the highest Science mark.
np.max(data[:, 2])

95

In [35]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [39]:
#Increase Math marks of all students by 5.
d = data[:, 1] + 5
d

array([90, 97, 81, 70, 95])

In [43]:
#Find how many students are younger than 19.
len(data[data[:,0] < 19])

3

In [46]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:], axis=0)

array([81.6, 83.2])

In [47]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:, 1] >= 80) & (data[:,2] >= 80)] 

array([[19, 92, 88],
       [20, 90, 85]])

In [6]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

NameError: name 'data' is not defined